-- MySQL Script generated by MySQL Workbench
-- Thu Sep 22 21:26:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CitasMedicas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CitasMedicas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CitasMedicas` DEFAULT CHARACTER SET utf8 ;
USE `CitasMedicas` ;

-- -----------------------------------------------------
-- Table `CitasMedicas`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CitasMedicas`.`Paciente` (
  `idPaciente` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` BIGINT(10) NOT NULL,
  `fechaNacimiento` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `tipoAfiliacion` VARCHAR(45) NOT NULL,
  `EPS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CitasMedicas`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CitasMedicas`.`Medico` (
  `idMedico` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` BIGINT(10) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CitasMedicas`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CitasMedicas`.`Cita` (
  `idCita` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `consultorio` VARCHAR(45) NOT NULL,
  `idPaciente` INT NOT NULL,
  `idMedico` INT NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `idPaciente_idx` (`idPaciente` ASC) VISIBLE,
  INDEX `idMedico_idx` (`idMedico` ASC) VISIBLE,
  CONSTRAINT `idMedico`
    FOREIGN KEY (`idMedico`)
    REFERENCES `CitasMedicas`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPaciente`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `CitasMedicas`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CitasMedicas`.`Diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CitasMedicas`.`Diagnostico` (
  `idDiagnostico` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `idCita` INT NOT NULL,
  PRIMARY KEY (`idDiagnostico`),
  INDEX `idCita_idx` (`idCita` ASC) VISIBLE,
  CONSTRAINT `idCita`
    FOREIGN KEY (`idCita`)
    REFERENCES `CitasMedicas`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CitasMedicas`.`Formula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CitasMedicas`.`Formula` (
  `idFormula` INT NOT NULL,
  `fechaVecimiento` VARCHAR(45) NOT NULL,
  `idDiagnostico` INT NOT NULL,
  PRIMARY KEY (`idFormula`),
  INDEX `idDiagnostico_idx` (`idDiagnostico` ASC) VISIBLE,
  CONSTRAINT `idDiagnostico`
    FOREIGN KEY (`idDiagnostico`)
    REFERENCES `CitasMedicas`.`Diagnostico` (`idDiagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CitasMedicas`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CitasMedicas`.`Medicamento` (
  `idMedicamento` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `referencia` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMedicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CitasMedicas`.`Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CitasMedicas`.`Detalle` (
  `idMedicamento` INT NOT NULL,
  `idFormula` INT NOT NULL,
  INDEX `idMedicamento_idx` (`idMedicamento` ASC) VISIBLE,
  INDEX `idFormula_idx` (`idFormula` ASC) VISIBLE,
  CONSTRAINT `idMedicamento`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `CitasMedicas`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idFormula`
    FOREIGN KEY (`idFormula`)
    REFERENCES `CitasMedicas`.`Formula` (`idFormula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
